

def render_forca(erros):
    if erros == 0:
        print('------------     ')
        print('|          |   ')
        print('|             ')
        print('|               ')
        print('|                ')
        print('|           ')
        print('|         ')
        print('|         ')
    if erros == 1:
        print('------------     ')
        print('|          |   ')
        print('|          0   ')
        print('|               ')
        print('|                ')
        print('|           ')
        print('|         ')
        print('|         ')
    if erros == 2:
        print('------------     ')
        print('|          |   ')
        print('|          0   ')
        print('|          |     ')
        print('|                ')
        print('|           ')
        print('|         ')
        print('|         ')
    if erros == 3:
        print('------------     ')
        print('|          |   ')
        print('|          0   ')
        print('|         -|     ')
        print('|                ')
        print('|           ')
        print('|         ')
        print('|         ')
    if erros == 4:
        print('------------     ')
        print('|          |   ')
        print('|          0   ')
        print('|         -|-     ')
        print('|                ')
        print('|           ')
        print('|         ')
        print('|         ')
    if erros == 5:
        print('------------     ')
        print('|          |   ')
        print('|          0   ')
        print('|         -|-     ')
        print('|         /      ')
        print('|           ')
        print('|         ')
        print('|         ')
    if erros == 6:
        print('------------     ')
        print('|          |   ')
        print('|          0   ')
        print('|         -|-     ')
        print('|         / \     ')
        print('|           ')
        print('|        ')
        print('|')
        print(' Lamento! Você Perdeu! ')

    return ''

